const listCard = [
  {
    src: "/images/card.png",
    time: "1h 20m",
    title: "Photoshop Advance: Retouching with Master of Photoshop (2023) ...",
    instructor: "Jacob Smoothy",
    star: "4/5",
    currentPrice: "80$",
    defaultPrice: "100$",
    viewer: "(1,000,000)",
  },
  {
    src: "/images/card1.png",
    time: "1h 20m",
    title:
      "Photoshop Advance: Retouching with Master of Photoshop (2023) with Master of Photoshop (2023), with Master of Photoshop (2023), with Master of Photoshop (2023)",
    instructor: "Jacob Andree",
    star: "4/5",
    currentPrice: "80$",
    defaultPrice: "100$",
    viewer: "(1,000,000)",
  },
  {
    src: "/images/card2.png",
    time: "1h 20m",
    title: "Photoshop Advance: Retouching with Master of Photoshop (2023) ...",
    instructor: "Jacob Andree",
    star: "4/5",
    currentPrice: "80$",
    defaultPrice: "130$",
    viewer: "(150,000)",
  },
  {
    src: "/images/card.png",
    time: "1h 20m",
    title: "Photoshop Advance: Retouching with Master of Photoshop (2023) ...",
    instructor: "Jacod Andree",
    star: "4/5",
    currentPrice: "50$",
    defaultPrice: "120$",
    viewer: "(1,000,000)",
  },
  {
    src: "/images/card.png",
    time: "1h 10m",
    title: "Photoshop Advance: Retouching with Master of Photoshop (2023) ...",
    instructor: "Jacod Andree",
    star: "4/5",
    currentPrice: "50$",
    defaultPrice: "120$",
    viewer: "(1,000,000)",
  },
  {
    src: "/images/card.png",
    time: "1h 40m",
    title: "Photoshop Advance: Retouching with Master of Photoshop (2023) ...",
    instructor: "Jacod Andree",
    star: "4/5",
    currentPrice: "50$",
    defaultPrice: "120$",
    viewer: "(1,000,000)",
  },
];

export { listCard };
